// Implementation file for parser generated by fsyacc
module DPar
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 1 "DPar.fsy"

open Absyn

# 10 "DPar.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | COLON
  | DOT
  | LBRACK
  | RBRACK
  | EXPOSE
  | FSLASH
  | DASH
  | COMMA
  | FROM
  | USER
  | INT of (int)
  | CPATH of (string * string)
  | NAME of (string)
  | WPATH of (string)
  | RUNCMD of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_COLON
    | TOKEN_DOT
    | TOKEN_LBRACK
    | TOKEN_RBRACK
    | TOKEN_EXPOSE
    | TOKEN_FSLASH
    | TOKEN_DASH
    | TOKEN_COMMA
    | TOKEN_FROM
    | TOKEN_USER
    | TOKEN_INT
    | TOKEN_CPATH
    | TOKEN_NAME
    | TOKEN_WPATH
    | TOKEN_RUNCMD
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startMain
    | NONTERM_Main
    | NONTERM_File
    | NONTERM_BaseImg
    | NONTERM_Instrs
    | NONTERM_Instr
    | NONTERM_WPath
    | NONTERM_CPath
    | NONTERM_Runcmd
    | NONTERM_Expose
    | NONTERM_Ports
    | NONTERM_User
    | NONTERM_Version
    | NONTERM_DottedName
    | NONTERM_DashedName

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | COLON  -> 1 
  | DOT  -> 2 
  | LBRACK  -> 3 
  | RBRACK  -> 4 
  | EXPOSE  -> 5 
  | FSLASH  -> 6 
  | DASH  -> 7 
  | COMMA  -> 8 
  | FROM  -> 9 
  | USER  -> 10 
  | INT _ -> 11 
  | CPATH _ -> 12 
  | NAME _ -> 13 
  | WPATH _ -> 14 
  | RUNCMD _ -> 15 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_COLON 
  | 2 -> TOKEN_DOT 
  | 3 -> TOKEN_LBRACK 
  | 4 -> TOKEN_RBRACK 
  | 5 -> TOKEN_EXPOSE 
  | 6 -> TOKEN_FSLASH 
  | 7 -> TOKEN_DASH 
  | 8 -> TOKEN_COMMA 
  | 9 -> TOKEN_FROM 
  | 10 -> TOKEN_USER 
  | 11 -> TOKEN_INT 
  | 12 -> TOKEN_CPATH 
  | 13 -> TOKEN_NAME 
  | 14 -> TOKEN_WPATH 
  | 15 -> TOKEN_RUNCMD 
  | 18 -> TOKEN_end_of_input
  | 16 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startMain 
    | 1 -> NONTERM_Main 
    | 2 -> NONTERM_File 
    | 3 -> NONTERM_File 
    | 4 -> NONTERM_BaseImg 
    | 5 -> NONTERM_Instrs 
    | 6 -> NONTERM_Instrs 
    | 7 -> NONTERM_Instr 
    | 8 -> NONTERM_Instr 
    | 9 -> NONTERM_Instr 
    | 10 -> NONTERM_Instr 
    | 11 -> NONTERM_Instr 
    | 12 -> NONTERM_Instr 
    | 13 -> NONTERM_Instr 
    | 14 -> NONTERM_WPath 
    | 15 -> NONTERM_CPath 
    | 16 -> NONTERM_Runcmd 
    | 17 -> NONTERM_Expose 
    | 18 -> NONTERM_Expose 
    | 19 -> NONTERM_Expose 
    | 20 -> NONTERM_Ports 
    | 21 -> NONTERM_Ports 
    | 22 -> NONTERM_User 
    | 23 -> NONTERM_User 
    | 24 -> NONTERM_User 
    | 25 -> NONTERM_Version 
    | 26 -> NONTERM_Version 
    | 27 -> NONTERM_Version 
    | 28 -> NONTERM_Version 
    | 29 -> NONTERM_Version 
    | 30 -> NONTERM_Version 
    | 31 -> NONTERM_Version 
    | 32 -> NONTERM_DottedName 
    | 33 -> NONTERM_DottedName 
    | 34 -> NONTERM_DashedName 
    | 35 -> NONTERM_DashedName 
    | 36 -> NONTERM_DashedName 
    | 37 -> NONTERM_DashedName 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 18 
let _fsyacc_tagOfErrorTerminal = 16

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | COLON  -> "COLON" 
  | DOT  -> "DOT" 
  | LBRACK  -> "LBRACK" 
  | RBRACK  -> "RBRACK" 
  | EXPOSE  -> "EXPOSE" 
  | FSLASH  -> "FSLASH" 
  | DASH  -> "DASH" 
  | COMMA  -> "COMMA" 
  | FROM  -> "FROM" 
  | USER  -> "USER" 
  | INT _ -> "INT" 
  | CPATH _ -> "CPATH" 
  | NAME _ -> "NAME" 
  | WPATH _ -> "WPATH" 
  | RUNCMD _ -> "RUNCMD" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | COLON  -> (null : System.Object) 
  | DOT  -> (null : System.Object) 
  | LBRACK  -> (null : System.Object) 
  | RBRACK  -> (null : System.Object) 
  | EXPOSE  -> (null : System.Object) 
  | FSLASH  -> (null : System.Object) 
  | DASH  -> (null : System.Object) 
  | COMMA  -> (null : System.Object) 
  | FROM  -> (null : System.Object) 
  | USER  -> (null : System.Object) 
  | INT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | CPATH _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | NAME _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | WPATH _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | RUNCMD _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 0us; 2us; 1us; 65535us; 0us; 4us; 2us; 65535us; 4us; 5us; 10us; 11us; 2us; 65535us; 4us; 10us; 10us; 10us; 2us; 65535us; 4us; 17us; 10us; 17us; 2us; 65535us; 4us; 23us; 10us; 23us; 2us; 65535us; 4us; 22us; 10us; 22us; 1us; 65535us; 18us; 19us; 2us; 65535us; 30us; 31us; 33us; 34us; 1us; 65535us; 20us; 21us; 2us; 65535us; 8us; 9us; 15us; 16us; 4us; 65535us; 38us; 42us; 39us; 40us; 46us; 47us; 50us; 51us; 4us; 65535us; 38us; 43us; 39us; 41us; 40us; 44us; 49us; 52us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; 7us; 10us; 13us; 16us; 19us; 22us; 24us; 27us; 29us; 32us; 37us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 1us; 1us; 2us; 2us; 3us; 1us; 3us; 1us; 4us; 1us; 4us; 1us; 4us; 1us; 4us; 2us; 5us; 6us; 1us; 6us; 1us; 7us; 1us; 8us; 1us; 8us; 1us; 8us; 1us; 8us; 1us; 9us; 1us; 10us; 1us; 10us; 1us; 11us; 1us; 11us; 1us; 12us; 1us; 13us; 1us; 14us; 1us; 15us; 1us; 16us; 3us; 17us; 18us; 19us; 1us; 18us; 1us; 18us; 1us; 19us; 1us; 19us; 2us; 20us; 21us; 1us; 21us; 1us; 21us; 2us; 22us; 24us; 1us; 23us; 1us; 24us; 3us; 25us; 29us; 30us; 4us; 26us; 27us; 28us; 31us; 2us; 27us; 31us; 1us; 28us; 1us; 29us; 1us; 30us; 1us; 31us; 2us; 32us; 33us; 2us; 32us; 33us; 1us; 33us; 4us; 34us; 35us; 36us; 37us; 2us; 34us; 37us; 2us; 35us; 36us; 1us; 36us; 1us; 37us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 8us; 11us; 13us; 15us; 17us; 19us; 21us; 24us; 26us; 28us; 30us; 32us; 34us; 36us; 38us; 40us; 42us; 44us; 46us; 48us; 50us; 52us; 54us; 56us; 60us; 62us; 64us; 66us; 68us; 71us; 73us; 75us; 78us; 80us; 82us; 86us; 91us; 94us; 96us; 98us; 100us; 102us; 105us; 108us; 110us; 115us; 118us; 121us; 123us; |]
let _fsyacc_action_rows = 53
let _fsyacc_actionTableElements = [|1us; 32768us; 9us; 6us; 0us; 49152us; 1us; 32768us; 0us; 3us; 0us; 16385us; 7us; 16386us; 5us; 18us; 9us; 13us; 10us; 20us; 12us; 25us; 13us; 12us; 14us; 24us; 15us; 26us; 0us; 16387us; 1us; 32768us; 13us; 7us; 1us; 32768us; 1us; 8us; 2us; 32768us; 11us; 39us; 13us; 38us; 0us; 16388us; 7us; 16389us; 5us; 18us; 9us; 13us; 10us; 20us; 12us; 25us; 13us; 12us; 14us; 24us; 15us; 26us; 0us; 16390us; 0us; 16391us; 1us; 32768us; 13us; 14us; 1us; 32768us; 1us; 15us; 2us; 32768us; 11us; 39us; 13us; 38us; 0us; 16392us; 0us; 16393us; 1us; 32768us; 11us; 27us; 0us; 16394us; 2us; 32768us; 11us; 36us; 13us; 35us; 0us; 16395us; 0us; 16396us; 0us; 16397us; 0us; 16398us; 0us; 16399us; 0us; 16400us; 2us; 16401us; 1us; 28us; 8us; 30us; 1us; 32768us; 11us; 29us; 0us; 16402us; 1us; 32768us; 11us; 32us; 0us; 16403us; 1us; 16404us; 8us; 33us; 1us; 32768us; 11us; 32us; 0us; 16405us; 1us; 16406us; 11us; 37us; 0us; 16407us; 0us; 16408us; 2us; 16409us; 2us; 45us; 7us; 48us; 2us; 16410us; 2us; 45us; 7us; 48us; 1us; 16411us; 7us; 48us; 0us; 16412us; 0us; 16413us; 0us; 16414us; 0us; 16415us; 1us; 32768us; 11us; 46us; 1us; 16416us; 2us; 45us; 0us; 16417us; 2us; 32768us; 11us; 50us; 13us; 49us; 1us; 16418us; 7us; 48us; 1us; 16419us; 2us; 45us; 0us; 16420us; 0us; 16421us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 2us; 3us; 5us; 6us; 14us; 15us; 17us; 19us; 22us; 23us; 31us; 32us; 33us; 35us; 37us; 40us; 41us; 42us; 44us; 45us; 48us; 49us; 50us; 51us; 52us; 53us; 54us; 57us; 59us; 60us; 62us; 63us; 65us; 67us; 68us; 70us; 71us; 72us; 75us; 78us; 80us; 81us; 82us; 83us; 84us; 86us; 88us; 89us; 92us; 94us; 96us; 97us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 2us; 1us; 2us; 4us; 1us; 2us; 1us; 4us; 1us; 2us; 2us; 1us; 1us; 1us; 1us; 1us; 1us; 3us; 3us; 1us; 3us; 1us; 1us; 2us; 1us; 1us; 2us; 2us; 2us; 2us; 3us; 2us; 3us; 2us; 2us; 3us; 3us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 3us; 4us; 4us; 5us; 5us; 5us; 5us; 5us; 5us; 5us; 6us; 7us; 8us; 9us; 9us; 9us; 10us; 10us; 11us; 11us; 11us; 12us; 12us; 12us; 12us; 12us; 12us; 12us; 13us; 13us; 14us; 14us; 14us; 14us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16385us; 65535us; 16387us; 65535us; 65535us; 65535us; 16388us; 65535us; 16390us; 16391us; 65535us; 65535us; 65535us; 16392us; 16393us; 65535us; 16394us; 65535us; 16395us; 16396us; 16397us; 16398us; 16399us; 16400us; 65535us; 65535us; 16402us; 65535us; 16403us; 65535us; 65535us; 16405us; 65535us; 16407us; 16408us; 65535us; 65535us; 65535us; 16412us; 16413us; 16414us; 16415us; 65535us; 65535us; 16417us; 65535us; 65535us; 65535us; 16420us; 16421us; |]
let _fsyacc_reductions ()  =    [| 
# 206 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Absyn.dockerfile)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startMain));
# 215 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'File)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 31 "DPar.fsy"
                                                         DFile _1 
                   )
# 31 "DPar.fsy"
                 : Absyn.dockerfile));
# 226 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'BaseImg)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "DPar.fsy"
                                                         [_1]      
                   )
# 38 "DPar.fsy"
                 : 'File));
# 237 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'BaseImg)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'Instrs)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "DPar.fsy"
                                                         _1 :: _2  
                   )
# 39 "DPar.fsy"
                 : 'File));
# 249 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'Version)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 46 "DPar.fsy"
                                                         BaseImage(_2, Tag _4)     
                   )
# 46 "DPar.fsy"
                 : 'BaseImg));
# 261 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Instr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 53 "DPar.fsy"
                                                         [_1]        
                   )
# 53 "DPar.fsy"
                 : 'Instrs));
# 272 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Instr)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'Instrs)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 54 "DPar.fsy"
                                                         _1 :: _2    
                   )
# 54 "DPar.fsy"
                 : 'Instrs));
# 284 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 61 "DPar.fsy"
                                                         Var _1                    
                   )
# 61 "DPar.fsy"
                 : 'Instr));
# 295 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'Version)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 62 "DPar.fsy"
                                                         BaseImage(_2, Tag _4)     
                   )
# 62 "DPar.fsy"
                 : 'Instr));
# 307 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'WPath)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 63 "DPar.fsy"
                                                         Workdir _1                
                   )
# 63 "DPar.fsy"
                 : 'Instr));
# 318 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'Expose)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 64 "DPar.fsy"
                                                         Expose _2                 
                   )
# 64 "DPar.fsy"
                 : 'Instr));
# 329 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'User)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 65 "DPar.fsy"
                                                         User _2                   
                   )
# 65 "DPar.fsy"
                 : 'Instr));
# 340 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Runcmd)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 66 "DPar.fsy"
                                                         Run _1                    
                   )
# 66 "DPar.fsy"
                 : 'Instr));
# 351 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'CPath)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 67 "DPar.fsy"
                                                         Copy _1                   
                   )
# 67 "DPar.fsy"
                 : 'Instr));
# 362 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 75 "DPar.fsy"
                                                         WPath _1 
                   )
# 75 "DPar.fsy"
                 : 'WPath));
# 373 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string * string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 83 "DPar.fsy"
                                                         CPath _1 
                   )
# 83 "DPar.fsy"
                 : 'CPath));
# 384 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 91 "DPar.fsy"
                                                         Cmd _1 
                   )
# 91 "DPar.fsy"
                 : 'Runcmd));
# 395 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 98 "DPar.fsy"
                                                         Port _1                    
                   )
# 98 "DPar.fsy"
                 : 'Expose));
# 406 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 99 "DPar.fsy"
                                                         PortM (_1, _3)             
                   )
# 99 "DPar.fsy"
                 : 'Expose));
# 418 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'Ports)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 100 "DPar.fsy"
                                                         Ports (_1 :: _3)           
                   )
# 100 "DPar.fsy"
                 : 'Expose));
# 430 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 107 "DPar.fsy"
                                                         [_1]     
                   )
# 107 "DPar.fsy"
                 : 'Ports));
# 441 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'Ports)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 108 "DPar.fsy"
                                                         _1 :: _3 
                   )
# 108 "DPar.fsy"
                 : 'Ports));
# 453 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 116 "DPar.fsy"
                                                         (Some _1, None)          
                   )
# 116 "DPar.fsy"
                 : 'User));
# 464 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 117 "DPar.fsy"
                                                         (None, Some _1)          
                   )
# 117 "DPar.fsy"
                 : 'User));
# 475 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 118 "DPar.fsy"
                                                         (Some _1, Some _2)      
                   )
# 118 "DPar.fsy"
                 : 'User));
# 487 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 125 "DPar.fsy"
                                                         _1                              
                   )
# 125 "DPar.fsy"
                 : 'Version));
# 498 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 126 "DPar.fsy"
                                                         string _1                       
                   )
# 126 "DPar.fsy"
                 : 'Version));
# 509 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'DottedName)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 127 "DPar.fsy"
                                                         string _1 + "." + _2            
                   )
# 127 "DPar.fsy"
                 : 'Version));
# 521 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'DashedName)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 128 "DPar.fsy"
                                                         string _1 + "-" + _2            
                   )
# 128 "DPar.fsy"
                 : 'Version));
# 533 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'DottedName)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 129 "DPar.fsy"
                                                         string _1 + "." + _2            
                   )
# 129 "DPar.fsy"
                 : 'Version));
# 545 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'DashedName)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 130 "DPar.fsy"
                                                         string _1 + "-" + _2            
                   )
# 130 "DPar.fsy"
                 : 'Version));
# 557 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'DottedName)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'DashedName)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 131 "DPar.fsy"
                                                         string _1 + "." + _2 + "-" + _3 
                   )
# 131 "DPar.fsy"
                 : 'Version));
# 570 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 138 "DPar.fsy"
                                                         string _2               
                   )
# 138 "DPar.fsy"
                 : 'DottedName));
# 581 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'DottedName)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 139 "DPar.fsy"
                                                         string _2 + "." + _3    
                   )
# 139 "DPar.fsy"
                 : 'DottedName));
# 593 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 146 "DPar.fsy"
                                                         string _2               
                   )
# 146 "DPar.fsy"
                 : 'DashedName));
# 604 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 147 "DPar.fsy"
                                                         string _2               
                   )
# 147 "DPar.fsy"
                 : 'DashedName));
# 615 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'DottedName)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 148 "DPar.fsy"
                                                         string _2 + "." + _3    
                   )
# 148 "DPar.fsy"
                 : 'DashedName));
# 627 "DPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'DashedName)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 149 "DPar.fsy"
                                                         string _2 + "-" + _3    
                   )
# 149 "DPar.fsy"
                 : 'DashedName));
|]
# 640 "DPar.fs"
let tables () : FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 19;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let Main lexer lexbuf : Absyn.dockerfile =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
